name: Build & Push Docker Camera App

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set version automatically (example: 1.0.23)
      - name: Set version
        run: echo "VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Single build with multiple tags
      - name: Build Docker image
        run: |
          docker build \
            -t pratham4563/poc-camera-app:latest \
            -t pratham4563/poc-camera-app:${VERSION} \
            .

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push pratham4563/poc-camera-app:latest
          docker push pratham4563/poc-camera-app:${VERSION}

      - name: Done
        run: echo "âœ… Image built and pushed successfully"
